version: '3.7'

services:
    app:
      build:
        context: .
      container_name: tabload
      hostname: tabload
      environment:
        DB_HOST: db
        DB_PORT: 5432
        DB_USER: postgres
        DB_PASS: example
      ports:
          - "8080:8080"
      depends_on:
          - mockdb

    mockdb:
        image: postgres
        restart: always
        container_name: db
        hostname: db
        environment:
            POSTGRES_PASSWORD: example
        ports:
            - "5432:5432"

